export const STOCKS = [
  { ticker: 'AAPL', name: 'Apple Inc.' },
  { ticker: 'MSFT', name: 'Microsoft Corp.' },
  { ticker: 'GOOGL', name: 'Alphabet Inc.' },
  { ticker: 'AMZN', name: 'Amazon.com Inc.' },
  { ticker: 'NVDA', name: 'NVIDIA Corp.' },
  { ticker: 'META', name: 'Meta Platforms Inc.' },
  { ticker: 'TSLA', name: 'Tesla Inc.' },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway' },
  { ticker: 'LLY', name: 'Eli Lilly and Co.' },
  { ticker: 'JPM', name: 'JPMorgan Chase & Co.' },
  { ticker: 'V', name: 'Visa Inc.' },
  { ticker: 'XOM', name: 'Exxon Mobil Corp.' },
  { ticker: 'UNH', name: 'UnitedHealth Group' },
  { ticker: 'MA', name: 'Mastercard Inc.' },
  { ticker: 'JNJ', name: 'Johnson & Johnson' },
  { ticker: 'HD', name: 'The Home Depot Inc.' },
  { ticker: 'PG', name: 'Procter & Gamble Co.' },
  { ticker: 'AVGO', name: 'Broadcom Inc.' },
  { ticker: 'COST', name: 'Costco Wholesale' },
  { ticker: 'MRK', name: 'Merck & Co. Inc.' },
  { ticker: 'ABBV', name: 'AbbVie Inc.' },
  { ticker: 'CVX', name: 'Chevron Corp.' },
  { ticker: 'KO', name: 'The Coca-Cola Co.' },
  { ticker: 'PEP', name: 'PepsiCo Inc.' },
  { ticker: 'ADBE', name: 'Adobe Inc.' },
  { ticker: 'NFLX', name: 'Netflix Inc.' },
  { ticker: 'AMD', name: 'Advanced Micro Devices' },
  { ticker: 'INTC', name: 'Intel Corp.' },
  { ticker: 'CRM', name: 'Salesforce Inc.' },
  { ticker: 'ACN', name: 'Accenture PLC' },
  { ticker: 'MCD', name: "McDonald's Corp." },
  { ticker: 'TXN', name: 'Texas Instruments' },
  { ticker: 'WMT', name: 'Walmart Inc.' },
  { ticker: 'NKE', name: 'Nike Inc.' },
  { ticker: 'ORCL', name: 'Oracle Corp.' },
  { ticker: 'BAC', name: 'Bank of America Corp.' },
  { ticker: 'AMGN', name: 'Amgen Inc.' },
  { ticker: 'QCOM', name: 'QUALCOMM Inc.' },
  { ticker: 'IBM', name: 'IBM Corp.' },
  { ticker: 'GE', name: 'General Electric Co.' },
  { ticker: 'CAT', name: 'Caterpillar Inc.' },
  { ticker: 'HON', name: 'Honeywell International' },
  { ticker: 'BA', name: 'The Boeing Co.' },
  { ticker: 'GS', name: 'Goldman Sachs Group' },
  { ticker: 'MS', name: 'Morgan Stanley' },
  { ticker: 'MMM', name: '3M Co.' },
  { ticker: 'RTX', name: 'RTX Corp.' },
  { ticker: 'DE', name: 'Deere & Co.' },
  { ticker: 'UBER', name: 'Uber Technologies' },
  { ticker: 'LYFT', name: 'Lyft Inc.' },
];
